### PR TITLE
src: fix Date.addMonth

### PR DESCRIPTION
**Pull request by santigimeno**
- Adding 1 month from the 31st day of a month that is followed by a less than
  31-day month, sets the Date to the first day if the following following month.
  For example: if the base Date is the 31st of May, calling addMonth, sets the
  date to the 1st of July instead of the 1st of June.

### CODE REVIEW

**Comment by santigimeno** [comment]
I think the current behaviour does not cause any bugs in `cron-parser` but it is causing problems in `node-schedule` that depends on this. See: https://github.com/node-schedule/node-schedule/issues/145

**Comment by santigimeno** [comment]
The failure on Travis is fixed by https://github.com/node-schedule/node-schedule/issues/145 and is unrelated to this change

**Comment by santigimeno** [comment]
Updated PR link

**Comment by jonhester** [comment]
Looks good to me. This was a bit wonky before and the tests didn't adequately adjust the edge cases

**Comment by santigimeno** [comment]
@harrisiirak Thanks for the quick response!

**Comment by harrisiirak** [comment]
Yeah, no problem. Thank you for the fix!

**Pull request merged**
