### PR TITLE
src: fix PR #138 regression

### PR DESCRIPTION
**Pull request by santigimeno**
Fixes: https://github.com/harrisiirak/cron-parser/issues/139

### CODE REVIEW

**Comment by zhangxiang958** [comment]
@harrisiirak @santigimeno what time this pr will be merged ? i want a newer package

**Comment by harrisiirak** [comment]
@santigimeno thanks for the fix and PR!
@zhangxiang958 soon! I'll give a quick review to this and merge/release if there aren't any further issues.

**Comment by zhangxiang958** [comment]
@harrisiirak two day passed! this pr cannot be merged ? this package lead a bug in my application on production, what accurate time will the package updated???

**Comment by harrisiirak** [comment]
@zhangxiang958 

> two day passed! this pr cannot be merged ?
> this package lead a bug in my application on production

This remark is rather, how to say... disrespectful - time is really scarce resource, for everyone! We all have our obligations and daily chores to attend to. I'm giving my best effort while handling such issues and trying to find solutions as soon as possible.

I'm really sorry that issue happened. You could always revert to the latest known version that worked, while this was being fixed/reviewed. 

@santigimeno thanks for your fix and hard work! This seems to be fixing the issue we're experiencing here. However I updated your original test case to use the pattern that was causing the issue.

**Comment by zhangxiang958** [comment]
@harrisiirak sorry about that comment. i should be more patient, thank you for your work, this package really helpful.

**Pull request merged**
