### PR TITLE
Implemented reverse directional cron date searching capabilities

### PR DESCRIPTION
**Pull request by faazshift**
One of my personal projects depends on the ability to find previous cron intervals. So I went ahead and implemented such in a fully backwards-compatible manner. After the fact, I noticed there was already an open issue relating to this (#48). In my basic testing, it works exactly as expected. However, I haven't written any tests for this added functionality yet.

### CODE REVIEW

**Comment by harrisiirak** [comment]
@faazshift nice! Although tests would be nice :) Will go through the code when I've a bit more time.

**Comment by faazshift** [comment]
@harrisiirak Happy to contribute! :) I certainly plan to add tests when I have a little more time myself.

**Comment by faazshift** [comment]
@harrisiirak I've made further improvements, added a few tests, and caught my fork up. Let me know if there are other types of tests you think would be valuable to add.

**Comment by harrisiirak** [comment]
@faazshift sorry about the delay. I'm trying to find the time to review and test the changes.

**Comment by harrisiirak** [comment]
@faazshift ok, looks good. I'm thinking that maybe we could rename `previous` to `prev`. But that is rather minor.

@santigimeno what do you think?

**Comment by faazshift** [comment]
@harrisiirak Done.

**Comment by santigimeno** [comment]
@harrisiirak i'll try to at this tomorrow

**Comment by harrisiirak** [comment]
@santigimeno if there aren't any objections I'm going to merge this in the following days.

**Comment by santigimeno** [comment]
@harrisiirak sorry, forgot about this. I'll try to look at it today or tomorrow.

**Pull request merged**
